name: RSS Feed Checker

on:
  schedule:
    - cron: '*/5 * * * *'   # Every 5 minutes
  workflow_dispatch:

jobs:
  rss_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore notified cache
        uses: actions/cache@v3
        id: cache
        with:
          path: notified.json
          key: rss-notified-${{ runner.os }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install xml2js node-fetch

      - name: Run RSS checker
        env:
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        run: node rss-check.js

      - name: Save notified cache
        uses: actions/cache@v3
        if: always()
        with:
          path: notified.json
          key: rss-notified-${{ runner.os }}
